# Copyright 2022 zhaoarden
name: GitHub Actions CI
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      # - name: Before Deploy2 ğŸ—ï¸
      #   run: echo "ğŸ 3${{ secrets.USER_NAME }}--4${{ env.secrets.SERVER_HOST }}"
      # - name: Connect to the serverğŸ”§
      #   run: ssh ${{ secrets.REMOTE_TARGET }}@${{ secrets.SERVER_HOST }} -A
      - name: Install ğŸ”§
        run: yarn install

      # # - name: Lint ğŸ§
      # #   run: npm run lint

      - name: Build ğŸ—ï¸
        run: yarn build
      # - name: Create Tag Release
      #   uses: beyond5959/create-release-github@v1
      #   with:
      #     tag_name: 7e80c809f34b653a75d675520a69e3295861f68a
      #     release_name: Release 7e80c809f34b653a75d675520a69e3295861f68a
      #     draft: false
      #     prerelease: false #Error: Bad credentials


      # - name: Test ğŸš¨
      #   run: npm test
      # ä¸Šä¼ æ‰“åŒ…èµ„æº
      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          # EXCLUDE: "/dist/, /node_modules/"

      # - name: Deploy
      #   uses: easingthemes/ssh-deploy@v2.0.7
      #   env:
      #       SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
      #       ARGS: '-avz --delete'
      #       SOURCE: 'build/'
      #       REMOTE_HOST: ${{ secrets.SERVER_HOST }}
      #       REMOTE_USER: ${{ secrets.USER_NAME }}
      #       TARGET: /var/www/susieTool # æœåŠ¡å™¨ç›®æ ‡è·¯å¾„

# å‚è€ƒæ–‡æ¡£
# https://juejin.cn/post/7028882363606106148